[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
dist-name = "spacy-ann-linker"
module = "spacy_ann"
author = "Spenser Stone"
author-email = "YongSuTK@gmail.com"
home-page = "https://github.com/PearlOnyx08/test_linker/"
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License"
]    
    
[tool.flit.metadata]

author = "test"
author-email = "YongSuTK@gmail.com"
home-page = ""

[tool.flit.scripts]
spacy_ann = "spacy_ann.cli:main"

[tool.flit.entrypoints."spacy_factories"]
ann_linker = "spacy_ann.ann_linker:AnnLinker"
remote_ann_linker = "spacy_ann.remote_ann_linker:RemoteAnnLinker"

[tool.flit.entrypoints."spacy_kb"]
get_candidates = "spacy_ann:get_candidates"
